name: Authenticate with AWS using AWS OICD and list all S3 bucket

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest
  
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::566027688242:role/GitHubOIDCRole
          aws-region: us-east-1
      
      - name: AWS CLI
        uses: aws s3 ls